=== R3mI29/project1-Web-/XML/page1.dtd
<!ENTITY % day "(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31)">
<!ENTITY % month "(janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre)">
<!--Fait par Rémi Millot et Virgile Krotlinski-->
<!ELEMENT match (date, lieu, equipes, score, infos)>

<!ELEMENT date EMPTY>
<!ATTLIST date
          day %day; #REQUIRED
          month %month; #REQUIRED
          year CDATA #REQUIRED>

<!ELEMENT lieu (ville, stade)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT stade (capacite, nom)>
<!ELEMENT capacite (#PCDATA)>
<!ELEMENT nom (#PCDATA)>

<!ELEMENT equipes (club+)>
<!ELEMENT club (entraineur)>
<!ATTLIST club
          id ID #REQUIRED
          nom CDATA #REQUIRED
          capitaine CDATA #REQUIRED>
<!ELEMENT entraineur (#PCDATA)>

<!ELEMENT score (marque, buteur*)>
<!ELEMENT marque (#PCDATA)>
<!ELEMENT buteur (joueur,description?)>
<!ELEMENT description (#PCDATA)>
<!ATTLIST buteur
          time CDATA #REQUIRED>
<!ELEMENT joueur (nom, prenom, numero, poste)>
<!ATTLIST joueur
          id ID #REQUIRED
          club IDREF #REQUIRED>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT poste (#PCDATA)>

<!ELEMENT infos (arbitre, spectateurs,fait-de-jeu*)>
<!ATTLIST infos
          competition (amical | LDC | Ligue1 | CdF | CdL) "Ligue1"
          format (90min | prolongation | tirs-au-but) "normal">
<!ELEMENT arbitre (#PCDATA)>
<!ELEMENT spectateurs (#PCDATA)>
<!ELEMENT fait-de-jeu (#PCDATA)>

=== R3mI29/project1-Web-/XML/page_xml_virgile.xml
<?xml version ="1.0" encoding ="UTF-8"?>
<!DOCTYPE match SYSTEM "page1.dtd">
<!--XML by Krotlinski Virgile-->
<match>
    <date day='25' month='août' year='2024'/>
    <lieu>
        <ville>Nantes</ville>
        <stade>
            <capacite>35332</capacite>
            <nom>La Beaujoire</nom>
        </stade>
    </lieu>
    <equipes>
        <club nom="AJ Auxerre" id="AJA" capitaine="Jubal Junior">
            <entraineur>Christophe Pelissier</entraineur>
        </club>
        <club nom="FC Nantes" id="FCN" capitaine="Jean-Charles Castelletto">
            <entraineur>Antoine Kombouaré</entraineur>
        </club>
    </equipes>
    <score>
        <marque>
            2-0
        </marque>
        <buteur time="14">
            <joueur id="Moses_FCN" club="FCN">
                <nom>Moses</nom>
                <prenom>Simon</prenom>
                <numero>27</numero>
                <poste>Ailier</poste>
            </joueur>
            <description>
                Un dégagement de Chirivella profite un peu par hasard à Simon qui peut défier Osho en un-contre-un. 
                Le Nigérian entre dans la surface, repique dans l'axe et tire du droit.Grosse faute de main de Léon, 
                le ballon termine dans les filets auxerrois.
            </description>
        </buteur>
        <buteur time="90+6">
            <joueur id="Guirassy_FCN" club="FCN">
                <nom>Guirassy</nom>
                <prenom>Bahereba</prenom>
                <numero>62</numero>
                <poste>Défenseur central</poste>
            </joueur>
            <description>
                Contre-attaque nantaise. Guirassy part du rond central, élimine Jubal et accélère.
                A l'entrée de la surface, il crochète derrière sa jambe d'appui pour laisser Osho sur les fesses,
                puis ajuste Léon d'un tir du droit.
            </description>
        </buteur>
    </score>
    <infos competition="Ligue_1" format="normal">
        <arbitre> Gaël Angoula </arbitre>
        <spectateurs>31077</spectateurs>
        <fait-de-jeu>Carton rouge à la 53ème minute pour l'attaquand d'Auxerre Ado Onaiwu.</fait-de-jeu>
    </infos>

</match>

=== R3mI29/project1-Web-/XML/page_xml_rémi.xml
<?xml version ="1.0" encoding ="UTF-8"?>
<!DOCTYPE match SYSTEM "page1.dtd">
<!--Fait par Rémi-->
<match>
    <date day="16" month="avril" year="2023"/>
    <lieu>
        <ville>Auxerre</ville>
        <stade>
            <capacite>18541</capacite>
            <nom>Abbé-Deschamps</nom>
        </stade>
    </lieu>
    <equipes>
        <club  id="AJA" nom="AJauxerre" capitaine="Birama Touré">
            <entraineur>Christophe Pelissier</entraineur>
        </club>
        <club id="FCN" nom="FCNantes" capitaine="Alban Lafont">
            <entraineur>Antoine Kombouaré</entraineur>
        </club>
    </equipes>
    <score>
        <marque>2-1</marque>
        <buteur time ="4">
            <joueur id="Jubal_aja" club="AJA">
                <nom>Jubal</nom>
                <prenom>Jr</prenom>
                <numero>4</numero>
                <poste>défenseur</poste>
            </joueur>
            <description>But sur penalty</description>
        </buteur>
        <buteur time ="43">
            <joueur id="Da_Costa_AJA" club="AJA">
                <nom>Da Costa</nom>
                <prenom>Nuno</prenom>
                <numero>9</numero>
                <poste>attaquant</poste>
            </joueur>
            <description>erreur du gardien</description>
        </buteur>
        <buteur time ="54">
            <joueur id="Mostafa_FCN" club="FCN">
                <nom>Mostafa</nom>
                <prenom>Mohamed</prenom>
                <numero>31</numero>
                <poste>defenseur</poste>
            </joueur>
            <description>But de la tête</description>
        </buteur>
    </score>
    <infos competition="Ligue_1" format="normal">
        <arbitre>Eric Wattellier</arbitre>
        <spectateurs>15,714</spectateurs>
        <fait-de-jeu></fait-de-jeu>
    </infos>
</match>

=== R3mI29/project1-Web-/XML/page_xml_rémi2.xml
<?xml version ="1.0" encoding ="UTF-8"?>
<!DOCTYPE match SYSTEM "page1.dtd">
<!--Fait par Rémi-->
<match>
    <date day="23" month="janvier" year="2018"/>
    <lieu>
        <ville>Nantes</ville>
        <stade>
            <capacite>38500</capacite>
            <nom>La Beaujoire</nom>
        </stade>
    </lieu>
    <equipes>
        <club  id="FCN" nom="FCNantes" capitaine="Valentin Rongier">
            <entraineur>Claudio Ranieri</entraineur>
        </club>
        <club id="AJA" nom="AJauxerre" capitaine="Birama Touré">
            <entraineur>Pablo Correa</entraineur>
        </club>
    </equipes>
    <score>
        <marque>3-4</marque>
        <buteur time ="6">
            <joueur id="Konaté_aja" club="AJA">
                <nom>Konaté</nom>
                <prenom>Brahim</prenom>
                <numero>6</numero>
                <poste>Millieu de terrain</poste>
            </joueur>
            <description>But du droit</description>
        </buteur>
        <buteur time ="32">
            <joueur id="Pallois_FCN" club="AJA">
                <nom>Pallois</nom>
                <prenom>Nicolas</prenom>
                <numero>4</numero>
                <poste>défenseur</poste>
            </joueur>
            <description>But contre son camps</description>
        </buteur>
        <buteur time ="34">
            <joueur id="Ayé_AJA" club="AJA">
                <nom>Ayé</nom>
                <prenom>Floriant</prenom>
                <numero>11</numero>
                <poste>attaquant</poste>
            </joueur>
            <description>But du gauche</description>
        </buteur>
        <buteur time ="38">
            <joueur id="Thomasson_FCN" club="FCN">
                <nom>Thomasson</nom>
                <prenom>Adrien</prenom>
                <numero>8</numero>
                <poste>Millieu de terrain</poste>
            </joueur>
            <description>But du gauche</description>
        </buteur>
        <buteur time ="51">
            <joueur id="Dubois_FCN" club="FCN">
                <nom>Léo</nom>
                <prenom>Ducbois</prenom>
                <numero>15</numero>
                <poste>défenseur</poste>
            </joueur>
            <description>But du gauche</description>
        </buteur>
        <buteur time ="65">
            <joueur id="Thomasson_FCN2" club="FCN">
                <nom>Thomasson</nom>
                <prenom>Adrien</prenom>
                <numero>8</numero>
                <poste>Millieu de terrain</poste>
            </joueur>
            <description>But du droit</description>
        </buteur>
        <buteur time ="76">
            <joueur id="Sangaré_AJA" club="AJA">
                <nom>Sangaré</nom>
                <prenom>Ibrahim</prenom>
                <numero>7</numero>
                <poste>attaquant</poste>
            </joueur>
            <description>But du droit</description>
        </buteur>
    </score>
    <infos competition="Coupe_de_France" format="normal">
        <arbitre>Amaury Delerue</arbitre>
        <spectateurs>36,567</spectateurs>
        <fait-de-jeu>élimination du FCN de la Coupe de France</fait-de-jeu>
    </infos>
</match>
